### ISSUE TITLE
Review wiki documentation for 18.3 release

### ISSUE THREAD

**Issue by sbailey** [desihub/tutorials#14]
Review and update wiki documentation as part of software release 18.3, including

* [x] https://desi.lbl.gov/trac/wiki/Pipeline/GettingStarted
* [x] https://desi.lbl.gov/trac/wiki/Pipeline/GettingStarted/Laptop
* [x] https://desi.lbl.gov/trac/wiki/Pipeline/GettingStarted/NERSC
* [x] https://desi.lbl.gov/trac/wiki/Pipeline/Install
* [x] https://desi.lbl.gov/trac/wiki/Computing/JupyterAtNERSC
* [x] https://desi.lbl.gov/trac/wiki/Computing/AccessNersc
* [x] https://desi.lbl.gov/trac/wiki/DataSystems/Tutorials
* [x] https://desi.lbl.gov/trac/wiki/Computing/Software/Guidelines
* [x] https://desi.lbl.gov/trac/wiki/Computing/UsingGit
* [x] https://desi.lbl.gov/trac/wiki/Pipeline/SpectroSoftwareReleases
* [x] https://desi.lbl.gov/trac/wiki/Pipeline/FormatsAndNumbering

Filing against tutorials in the spirit of documentation just to get a marker into the 18.3 project, even though the updates will be to the wiki rather than this repo itself.

**Comment by weaverba137** [comment]
A potentially big change that is planned for 18.3 is that desi_environment.sh will now only deal with releases that are on /global/common/software, not /global/common/${NERSC_HOST}.  So what do we do about 18.1 and earlier?

**Comment by weaverba137** [comment]
@sbailey, would it be possible for you to add a few sentences to https://desi.lbl.gov/trac/wiki/Pipeline/SpectroSoftwareReleases#Notesfromthe18.2ainstall ?

**Comment by sbailey** [comment]
I added some notes on 18.2a to https://desi.lbl.gov/trac/wiki/Pipeline/SpectroSoftwareReleases#Notesfromthe18.2ainstall

For the record, @weaverba137 also updated desi_environment.[c]sh so that it supports software releases in both the old and new location.

**Comment by sbailey** [comment]
I also reviewed and updated the NERSC and laptop getting started instructions.  Closing this ticket for 18.3.
