### ISSUE TITLE
simulating-desi-spectra tutorial broken for 19.2

### ISSUE THREAD

**Issue by sbailey** [desihub/tutorials#26]
@moustakas could you take a look at the simulating-desi-spectra.ipynb tutorial and fix it for software release 19.2 (or alternatively master if needed)?

@lastephey reports:

> simulating-desispectra
-cell 5 throws a lot of matplotlib warnings and eventually valueerrors out from qso_marker.make_templates()

We need to get this updated prior to the collaboration meeting tutorial session on Monday July 8.  If you can't do it by then (and preferably earlier) please let me know.

**Comment by weaverba137** [comment]
Fixed by #29
