### ISSUE TITLE
Notebooks require data that has been removed from NERSC

### ISSUE THREAD

**Issue by weaverba137** [desihub/tutorials#38]
The notebooks dc17a-truth.ipynb and redrock/RedrockOutputs.ipynb use `desi/datachallenge/dc17a-twopct/` which was recently removed from NERSC spinning disk.  Do we restore the data set, deprecate these notebooks or update them to use a different, *circa* 2020 data set?

**Comment by sbailey** [comment]
Would be best to replace the dc17a-truth.ipynb notebook with one that demonstrates how to look up simulation truth using a more recent reference run.
