### ISSUE TITLE
Replace dc17a-truth notebook

### ISSUE THREAD

**Issue by sbailey** [desihub/tutorials#40]
Replace the dc17a-truth notebook with one based upon a recent reference run, and rename it to get "dc17a" out of the name.

The current master copy has work in that direction from PR #39, but it stops on a cell that is trying to find truth grouped by brickname instead of by healpix.

The target truth is now in:

targets/{healpixgroup}/{healpix}/{dark|bright}/truth-{dark|bright}-{nside}-{healpix}.fits

where healpixgroup = healpix//64, healpix = NESTED healpix, and nside is usually 64.  `desimodel.footprint.radec2pix` is a convenience wrapper around healpy to take care of ra,dec in degrees to polar angles in radians while enforcing NESTED, etc.

**Comment by weaverba137** [comment]
@sbailey, since we have now removed the reference runs from disk, can we just close this. The notebook has already been moved to the 'archive' directory.

**Comment by weaverba137** [comment]
Closing issue since there are no objections.
