### ISSUE TITLE
Add tutorial about targeting masks

### ISSUE THREAD

**Issue by sbailey** [desihub/tutorials#44]
CMX vs. SV0 vs. main, obsconditions, mask bits, pointers to other documentation like https://desi.lbl.gov/trac/wiki/TargetSelectionWG#TargetSelectionAlgorithms, etc.

**Comment by geordie666** [comment]
See:

https://github.com/desihub/desitarget/blob/master/doc/nb/target-selection-bits-and-bitmasks.ipynb

Although I haven't tested it for a while (and it could certainly be expanded).

**Comment by sbailey** [comment]
Thanks @geordie666 .  I just added a link to that from the tutorials/README.md page.
