### ISSUE TITLE
Bug with plotspec function in simulating-desi-spectra

### ISSUE THREAD

**Issue by noahfranz13** [desihub/tutorials#49]
In the simulating-desi-spectra tutorial when the plotspec function is defined a loop is used to iterate over ['b', 'r', 'z'] using the variable x however within the loop x is never used, instead, only 'r' is used in its place. See below:

for x in ['b', 'r', 'z']:
        tmpmin, tmpmax = np.percentile(spectra.flux**['r']**[i], [1, 99])
        ymin = min(tmpmin, ymin)
        ymax = max(tmpmax, ymax)

Instead this worked better for me:

for x in ['b', 'r', 'z']:
        tmpmin, tmpmax = np.percentile(spectra.flux**[x]**[i], [1, 99])
        ymin = min(tmpmin, ymin)
        ymax = max(tmpmax, ymax)

**Comment by sbailey** [comment]
Good catch.  Could you please open a pull request with that fix?  ping me and @moustakas if there are any procedural hiccups with write permission, how to open a PR, etc.  Thanks.

**Comment by sbailey** [comment]
Fixed in PR #50.  Thanks.
