### ISSUE TITLE
Location of redshift database notebook?

### ISSUE THREAD

**Issue by weaverba137** [desihub/tutorials#69]
Historically the redshift database notebook was based on simulations, but in the very near future it will be tied to real data.  Is the simulations directory appropriate in that case?

**Comment by sbailey** [comment]
Good point.  When you update it to use real data, let's
* remove the sections about *loading* the database.  That should be documented elsewhere, but isn't really a broad-audience tutorial topic that we'd expect non-experts to learn or do.
* preserve the sections about *using* the database, with a focus on using a the edr/fuji load at NERSC.
* move it under a new database/ directory.  I had considered moving it under redrock/, but some uses of the database are for exposure/tile/fiberassign bookkeeping independent of the redshift parts of the database.

**Comment by weaverba137** [comment]
Sounds good to me, thank you.
