### ISSUE TITLE
Update Database Tutorial Notebook with new zpix

### ISSUE THREAD

**Issue by stephjuneau** [desihub/tutorials#81]
Depending on the solution between adding the targeting columns directly into `zpix` or creating a materialized view `zpix_target`, update the [Database Tutorial Notebook](https://github.com/desihub/tutorials/blob/main/database/spectroscopic-production-database.ipynb) accordingly to reflect the change.

**Comment by weaverba137** [comment]
I'm reasonably certain that the existing notebook does not include any examples related to this issue, so any update would be an entirely new example.

**Comment by weaverba137** [comment]
I'm concerned that tag 23.5 may be premature. Due to outside factors, the database tutorial notebook is still not vetted for public use.

**Comment by forero** [comment]
@weaverba137, sorry for rushing things. I'll get a new tag (`EDR`) ready by tomorrow afternoon. This will allow more time for adding more updates.

**Comment by weaverba137** [comment]
I don't think that was particularly rushed.  I would not recommend changing our current tagging convention right now.  Use `23.6` and simply mention in the top-level README that it corresponds to EDR.
