### ISSUE TITLE
Add instructions on how a non-DESI NERSC user can use a DESI notebook kernel.

### ISSUE THREAD

**Issue by forero** [desihub/tutorials#82]
Creating a new issue from this comment https://github.com/desihub/tutorials/issues/79#issuecomment-1557621979

> we need some instructions about how to set up a DESI notebook kernel. In principle this could be done with install_desi_kernel.sh, but I think it may be better to generate pre-made kernels for 22.5 and 23.1. Otherwise the public might start using unsupported kernels.

**Comment by forero** [comment]
The solution to this issue depends on testing these updates https://github.com/desihub/desimodules/pull/48

**Comment by weaverba137** [comment]
I have added `main` to the kernels in `/global/common/software/desi/kernels`.

**Comment by forero** [comment]
Resolved with this commit https://github.com/desihub/tutorials/commit/d9140aa8f89071a4fc79dbf1172a9b9a2304a353 .
