### ISSUE TITLE
Accessing the database using RA and Dec.

### ISSUE THREAD

**Issue by astro-fermi** [desihub/tutorials#92]
Dear Madam/Sir,

I just read the DESI EDR paper released today on arXiv (https://arxiv.org/pdf/2306.06308.pdf). Following this, I wanted to extract the redshift values and plot the corresponding spectra for a list of sources with known RA and Dec. I tried checking EDR_AnalyzeZcat.ipynb file but couldn't figure out how one can access the database by supplying the RA and Dec values. Please help me in this regard. Thank you.

**Comment by sbailey** [comment]
Thanks for the question, @astro-fermi .  Please re-post it at help.desi.lbl.gov and we'll answer it there.  We are trying to consolidate questions+answers there for the community to browse, and reserve github tickets for bug reports and development tracking.  Thanks.
